name: windows

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ 2.4, 2.5, 2.6, 2.7 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: rake setup
        shell: bash
      - name: Run Test
        run: |
          ridk enable
          rake test
    timeout-minutes: 15
